version: '2.1'
services:
  mock-service:
    build: mock-service
    image: mock-service
    depends_on:
      - kotlin-mongo
    environment:
      JAVA_OPTS: -Dmongo.host=kotlin-mongo -agentlib:jdwp=transport=dt_socket,server=y,address=1044,suspend=n
    ports:
      - "${MOCK_SERVICE_DEBUG_PORT:-1045}:1044"

  api-gateway:
    build: api-gateway
    image: api-gateway
    depends_on:
      - mock-service
    environment:
      JAVA_OPTS: -Dmock.service.url=mock-service:8080 -agentlib:jdwp=transport=dt_socket,server=y,address=1044,suspend=n
    ports:
      - "8080:8080"
      - "${API_GATEWAY_DEBUG_PORT:-1044}:1044"

  kotlin-mongo:
    image: mongo
    ports:
      - "27017:27017"